run_name: auto

# Architecture
encoder_type: vit_b_enc
decoder_type: unet_patched
input_size_min: 224
input_size_max: 224
resolution_step: 1 # for varying image resolutions
patch_size: 16 # encoder ViT patch size
patch_size_dec: 4 # Patched UNet decoder patch size
post_mlp: True # tanh MLP before quantizer, see ViT-VQGAN paper

# Quantizer
codebook_size: 8192
latent_dim: 32
norm_codes: True
codebook_weight: 1.0
quantizer_type: lucid
coef_ema_dead_code: 32.0
code_replacement_policy: batch_random
commitment_weight: 1.0
quantizer_ema_decay: 0.99
kmeans_init: False
orthogonal_reg_weight: 1.0 # just to be explicit

# Diffusion
num_train_timesteps: 1000 # number of diffusion steps during training
prediction_type: sample # diffusion target
beta_schedule: linear # noise schedule
cls_free_guidance_dropout: 0.0 # How often to drop out the conditioning
masked_cfg: False # Randomly mask out the tokens when using conditioning dropout
clip_sample: False # Only for logged images
loss_fn: smooth_l1
resolution_cond: False

# Train
dtype: bf16 # fp32, fp16 or bf16
warmup_epochs: 5
epochs: 20
opt: adamw
opt_betas: [0.9, 0.99]
blr: 0.0001 # base_lr = 1e-4, lr = base_lr * batch_size / 256
warmup_lr: 0.000001 # 1e-6
min_lr: 0.
batch_size: 96 # per GPU
save_ckpt_freq: 3 # in epochs
weight_decay: 0.05 # the default
find_unused_params: False
model_ema: False
# model_ema_decay: 0.9999
# model_ema_update_freq: 1 # in iterations

# Eval
step_eval: False
epoch_eval: True
eval_freq: 3
eval_metrics_freq: 3
eval_image_log_freq: 3
num_eval_metrics_samples: 5000 # Number of samples to use for evaluating image metrics during training.
num_logged_images: 1 # can't really (easily) visualize these so...
eval_noise_schedule: DDIMScheduler
num_eval_timesteps: 50
input_size_eval: 224
dist_eval: True

# Augmentation
use_random_rotations: True
near_orthogonal: True
rotation_resample_mode: bicubic

# Data
mask_value: 0
domain: depth
data_path: '/scratch/bdej/cohanlon/unsupervised/train'
eval_data_path: '/scratch/bdej/cohanlon/unsupervised/eval'

# Logging
log_wandb: True # Set to True to log to Weights & Biases
wandb_project: depth_tokenizer
wandb_entity: sarformer
wandb_run_name: auto
output_dir: 'output/auto'
log_codebook_usage: True # just to be explicit
show_user_warnings: False

# Misc.
device: cuda
num_workers: 110
cache_datasets: False
