run_name: auto

# Model
model: sarformer_s
cond_domains: ["rgb", "depth", "caption"]
target_size: 224
finetune: "/scratch/bdej/cohanlon/checkpoints/sarformer/model/pretrain/S_MAE_rgb-depth-caption/checkpoint-final.pth"

# Train
objective: lpl
loss_type: mse
distance_type: euclidean
dtype: bf16 # fp32, fp16 or bf16
warmup_epochs: 10
epochs: 100
opt: adamw
opt_betas: [0.9, 0.99]
blr: 0.0001 # base_lr = 1e-4, lr = base_lr * batch_size / 256
warmup_lr: 0.000001 # 1e-6
min_lr: 0.
batch_size: 32 # per GPU
save_ckpt_freq: 25 # in epochs
weight_decay: 0.05 # the default
lr_and_wd_scheduler: cosine

# Augmentation
full_img_size: 673
eff_img_size: 447
crop_std: 1e3
hflip: 0.0
vflip: 0.0

# Eval
eval_freq: 10
eval_metrics_freq: 25
eval_image_log_freq: 10
num_eval_metrics_samples: 416 # Number of samples to use for evaluating image metrics during training.
num_logged_images: 9
dist_eval: True
data_path: '/scratch/bdej/cohanlon/data/train'
eval_data_path: '/scratch/bdej/cohanlon/data/eval'

# Logging
log_wandb: True
wandb_project: model
wandb_entity: sarformer
wandb_run_name: auto
output_dir: '/scratch/bdej/cohanlon/checkpoints/sarformer/auto'
show_user_warnings: False
compute_grad_norm: True

# Misc.
device: cuda
num_workers: 110 # for data loaders